# Capfile with example murder config

require 'rubygems'
require 'murder'

set :application, 'example-app'

set :scm, 'git'
set :repository, 'ssh://git.example.com/my/app.git'
set :copy_exclude, '.git'

# use murder
set :deploy_via, :murder

# convenient hooks
after 'deploy:setup', 'murder:distribute_files' # setup remote murder support files on all hosts
before 'murder:start_seeding', 'murder:start_tracker' # let deploy manage the tracker as well
after 'murder:stop_seeding', 'murder:stop_tracker'

# define an app server role
role :app, 'w01', 'w02', 'w03', 'w04', 'w05'

# murder roles
role :tracker, 'tracker.example.com', :no_release => true
role :seeder, 'seeder.example.com', :no_release => true
role(:peers) { find_servers(:role => :app) }
